apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: v1
kind: Namespace
metadata:
  name: freepbx-sidecar
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-transit
---
apiVersion: v1
kind: Namespace
metadata:
  name: freepbx