# The headless Service provides a home for the DNS entries that the StatefulSet controllers 
# creates for each Pod that's part of the set. Because the headless Service is named mysql, 
# the Pods are accessible by resolving <pod-name>.mysql from within any other Pod 
# in the same Kubernetes cluster and namespace.

# The client Service, called mysql-read, is a normal Service with its own cluster IP 
# that distributes connections across all MySQL Pods that report being Ready. 
# The set of potential endpoints includes the primary MySQL server and all replicas.

# Note that only read queries can use the load-balanced client Service. 
# Because there is only one primary MySQL server, clients should connect directly 
# to the primary MySQL Pod (through its DNS entry within the headless Service) to execute writes.

# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql

---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.

apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
