apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
      app.kubernetes.io/name: vault
  serviceName: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        app.kubernetes.io/name: vault
    spec:
      containers:
      - name: vault
        image: escomputers/freepbx-k8s-vault:latest
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8100"
        - name: VAULT_TOKEN
          value: ""
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        ports:
        - name: vault-web
          containerPort: 8100
          protocol: TCP
        volumeMounts:
        - name: vault
          mountPath: /vault
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: vault
        emptyDir: {}