apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freepbx-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: vultr-block-storage